services:
  karing:
    image: ghcr.io/recelsus/karing:latest
    # Build locally instead of pulling from GHCR (uncomment below)
    # build:
    #   context: ..
    #   dockerfile: docker/Dockerfile
    container_name: karing
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Defaults are baked in the image; override with -e or here.
      KARING_DATA: "/var/lib/karing/karing.db"     # DB file path
      KARING_LOG_PATH: "/var/log/karing"           # Logs directory
      # KARING_BASE_PATH: /myapp
      # KARING_LIMIT: "100"
      # KARING_MAX_FILE_BYTES: "20971520"
      # KARING_MAX_TEXT_BYTES: "10485760"
      # KARING_TRUSTED_PROXY: "1"                  # trust proxy headers
      # KARING_NO_AUTH: "1"                        # dev only (disable auth)
    volumes:
      - karing-data:/var/lib/karing   # data dir
      - karing-logs:/var/log/karing   # logs dir

volumes:
  karing-data:
  karing-logs:
