services:
  karing-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: karing:dev
    container_name: karing-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Uncomment to override defaults during dev runs.
      # KARING_CONFIG: "/etc/karing/karing.json"
      # KARING_DATA: "/var/lib/karing/karing.dev.db"
      # KARING_LOG_PATH: "/var/log/karing"
      # KARING_BASE_PATH: /myapp
      # KARING_LIMIT: "100"
      # KARING_TRUSTED_PROXY: "1"
      # KARING_NO_AUTH: "1"
      KARING_WEB_UI: "1"
